### ISSUE TITLE
User Story - create a new profile when posting your first message

### ISSUE THREAD

**Issue by edgarfinn** [edgarfinn/Chatter-Social-Network#1]
As a new user wanting to join Chatter, I can create a new account when I post my first message, by entering an unused username followed by a message, so that I can build a network of interactions with other Chatter users.

Command: ```<username> -> <message>```

**Comment by edgarfinn** [comment]
- [x] #6 Identify command type
- [x] #7 Write ```userExists``` function
- [x] #8 Write ``` createNewUser``` function
- [x] #9 Scaffold ```post``` function
- [x] #10 Scaffold ```read``` function 
- [x] #11 Scaffold ```follow``` function 
- [x] #12 Scaffold ```wall``` function
- [x] #21 write ```updateStore``` function
