### ISSUE TITLE
User Story - Read a user's timeline

### ISSUE THREAD

**Issue by edgarfinn** [edgarfinn/Chatter-Social-Network#3]
As either a registered or unregistered user, I can view any existing user's timeline by typing their name in as a command, so that I can view all messages they have posted to Chatter in reverse-chronological order.

Command ```<username>```

**Comment by edgarfinn** [comment]
- [x] #24 write ```readTimeline```

- [x] #14 write ```sortPosts``` function

- [x] #15 write ```recency``` function

- [x] #16 write ```renderMessage``` function

complete scaffolded ```read``` function:

- iterate through sorted array of rendered message strings
- console.log message + newline
